### ISSUE TITLE
Implementation for commercial purposes

### ISSUE THREAD

**Issue by EstebanExplorer** [FarrandTom/social-distancing#1]
Hi Tom Farrand, thanks for such a fabulous job, I imagine the great effort and dedication, I want to know if I can carry out an implementation for commercial purposes?

Thank you in advance for your answer,

Cheers

**Comment by FarrandTom** [comment]
Hey Calidoso, 

This makes use of some methods from a research team in Italy (https://github.com/IIT-PAVIS/Social-Distancing). Their code is MIT licensed which has very limited reuse restrictions. I'm fine with the code that I have added to used therefore, from my perspective, you can reuse it for commercial purposes. 

All I would ask is that any code that is lifted is correctly attributed to the author :)

Cheers, 
Tom

(full disclaimer: I'm not a licensing expert and what I'm providing is not legal advice)

**Comment by calidoso** [comment]
Muchas gracias, por la respuesta.

**Comment by EstebanExplorer** [comment]
Thank you very much for the reply
